### ISSUE TITLE
显示TypeError: nextMessage.content.match is not a function报错

### ISSUE THREAD

**Issue by fuwei99** [Archeb/YOUChat_Proxy#23]
cookie有效，网页也能正常打开，但只要酒馆发送新消息就会报错

**Comment by fuwei99** [comment]
added 276 packages, and audited 277 packages in 11s

33 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
No proxy environment variable set, global proxy not configured.
本项目依赖Chrome或Edge浏览器，请勿关闭弹出的浏览器窗口。如果出现错误请检查是否已安装Chrome或Edge浏览器。
使用Chrome浏览器
已添加 #0 fancywork159@gmail.com
已添加 #1 hirotoby123@gmail.com
已添加 2 个 cookie，开始验证有效性（是否有订阅）
fancywork159@gmail.com 有效
hirotoby123@gmail.com 有效
验证完毕，有效cookie数量 2
YouChat proxy listening on port 8080
Proxy is currently running with no authentication
Custom mode: disabled
Mode rotation: disabled
Handling request of OpenAI format
message length:77
Using session fancywork159@gmail.com
Using model claude_3_5_sonnet
Custom mode is disabled, using default mode.
Using file upload mode
TypeError: nextMessage.content.match is not a function
    at formatMessages (file:///C:/Users/zhishang/Desktop/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/formatMessages.mjs:24:51)
    at YouProvider.getCompletion (file:///C:/Users/zhishang/Desktop/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/provider.mjs:349:30)
    at async IncomingMessage.<anonymous> (file:///C:/Users/zhishang/Desktop/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/index.mjs:110:3)
Handling request of OpenAI format
message length:77
Using session hirotoby123@gmail.com
Using model claude_3_5_sonnet
Custom mode is disabled, using default mode.
Using file upload mode
TypeError: nextMessage.content.match is not a function
    at formatMessages (file:///C:/Users/zhishang/Desktop/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/formatMessages.mjs:24:51)
    at YouProvider.getCompletion (file:///C:/Users/zhishang/Desktop/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/provider.mjs:349:30)
    at async IncomingMessage.<anonymous> (file:///C:/Users/zhishang/Desktop/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/index.mjs:110:3)
Handling request of OpenAI format
message length:77
Using session fancywork159@gmail.com
Using model claude_3_5_sonnet
Custom mode is disabled, using default mode.
Using file upload mode
TypeError: nextMessage.content.match is not a function
    at formatMessages (file:///C:/Users/zhishang/Desktop/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/formatMessages.mjs:24:51)
    at YouProvider.getCompletion (file:///C:/Users/zhishang/Desktop/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/provider.mjs:349:30)
    at async IncomingMessage.<anonymous> (file:///C:/Users/zhishang/Desktop/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/YOUChat_Proxy-450741ed553c1c716aea9c410f6d221cb2efb882/index.mjs:110:3)

**Comment by fuwei99** [comment]
好吧，原来是设置错了

**Comment by fuwei99** [comment]
chat completion source必须使用open ai

**Comment by fuwei99** [comment]
我记得之前的用claude也没问题呀

**Comment by fuwei99** [comment]
刚刚那个报错没有了，但是是时不时出现这个报错


Handling request of OpenAI format
message length:75
Using session fancywork159@gmail.com
Using model claude_3_5_sonnet
Custom mode is disabled, using default mode.
Generated random file name: yhuZJ6K41oMJ.docx
Using file upload mode
Local copy of formatted messages saved to: C:\Users\zhishang\Desktop\1CLAUDE\Claude\YOUChat_Proxy-bypass-cf\local_copy_formatted_messages.txt
Error: Failed to get nonce
    at YouProvider.getCompletion (file:///C:/Users/zhishang/Desktop/1CLAUDE/Claude/YOUChat_Proxy-bypass-cf/provider.mjs:381:22)
    at async IncomingMessage.<anonymous> (file:///C:/Users/zhishang/Desktop/1CLAUDE/Claude/YOUChat_Proxy-bypass-cf/index.mjs:110:3)
Handling request of OpenAI format
message length:75
Using session fancywork159@gmail.com
Using model claude_3_5_sonnet
Custom mode is disabled, using default mode.
Generated random file name: mqmizLVs6r-OSxW6.docx
Using file upload mode
Local copy of formatted messages saved to: C:\Users\zhishang\Desktop\1CLAUDE\Claude\YOUChat_Proxy-bypass-cf\local_copy_formatted_messages.txt
Error: Failed to get nonce
    at YouProvider.getCompletion (file:///C:/Users/zhishang/Desktop/1CLAUDE/Claude/YOUChat_Proxy-bypass-cf/provider.mjs:381:22)
    at async IncomingMessage.<anonymous> (file:///C:/Users/zhishang/Desktop/1CLAUDE/Claude/YOUChat_Proxy-bypass-cf/index.mjs:110:3)
